server:
  port: 8084
spring:
  application:
    name: producao-ms
  mvc:
    servlet:
      path: /api/producoes
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/producao-ms
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  rabbitmq:
    password: guest
    port: '5672'
    host: localhost
    username: guest
  flyway:
    enabled: true
    locations: 'classpath:db/migration'
    validate-on-migrate: false