version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: phillippimentafood-rabbitmq
    ports:
      - "5672:5672"    # Porta padrão do RabbitMQ
      - "15672:15672"  # Porta do console de gerenciamento
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest