INSERT INTO produtos (id_externo, categoria, nome, descricao, preco, data_criacao) VALUES (gen_random_uuid(), 'LANCHE', 'X  kids', 'Pão de brioche selado na chapa, hambúrguer e queijo mussarela.', 10.99, now());
INSERT INTO produtos (id_externo, categoria, nome, descricao, preco, data_criacao) VALUES (gen_random_uuid(), 'LANCHE', 'Bauru simples', 'Pão, hambúrguer, ovo, queijo, presunto, tomate, cebola e alface.', 12.90, now());
INSERT INTO produtos (id_externo, categoria, nome, descricao, preco, data_criacao) VALUES (gen_random_uuid(), 'LANCHE', 'X Frango', 'Pão, molho, hambúrguer, ovo, queijo, presunto, cheddar ou Catupiry, frango, tomate, cebola e alface.', 14.99, now());
INSERT INTO produtos (id_externo, categoria, nome, descricao, preco, data_criacao) VALUES (gen_random_uuid(), 'LANCHE', 'X Bacon', 'Pão, molho, hambúrguer, ovo, queijo, presunto, cheddar ou Catupiry, bacon, tomate, cebola e alface.', 16.99, now());
INSERT INTO produtos (id_externo, categoria, nome, descricao, preco, data_criacao) VALUES (gen_random_uuid(), 'LANCHE', 'X Especial', 'Pão, molho, hambúrguer, ovo, queijo, presunto, cheddar ou Catupiry, frango, carne, bacon, tomate, cebola e alface.', 18.99, now());
INSERT INTO produtos (id_externo, categoria, nome, descricao, preco, data_criacao) VALUES (gen_random_uuid(), 'LANCHE', 'X  Picanha Acebolado', 'Pão de brioche selado na chapa, hamburguer de pichanha, queijo cheddar, cebola assada na manteiga do sertão com queijo gratinado e fatias de bacon.', 22.99, now());

INSERT INTO produtos (id_externo, categoria, nome, descricao, preco, data_criacao) VALUES (gen_random_uuid(), 'ACOMPANHAMENTO', 'Batata Frita Pequena (200g)', 'Batatas selecionadas, crocantes por fora e incrivelmente macias por dentro.', 12.90, now());
INSERT INTO produtos (id_externo, categoria, nome, descricao, preco, data_criacao) VALUES (gen_random_uuid(), 'ACOMPANHAMENTO', 'Batata frita grande (400g)', 'Batatas selecionadas, crocantes por fora e incrivelmente macias por dentro.', 16.90, now());
INSERT INTO produtos (id_externo, categoria, nome, descricao, preco, data_criacao) VALUES (gen_random_uuid(), 'ACOMPANHAMENTO', 'Super Batata Cheddar (400g)', 'Batatas selecionadas, crocantes por fora e incrivelmente macias por dentro.', 21.90, now());
INSERT INTO produtos (id_externo, categoria, nome, descricao, preco, data_criacao) VALUES (gen_random_uuid(), 'ACOMPANHAMENTO', 'Anéis de cebola (200g)', 'Anéis de cebola empanados e dourados, crocantes e saborosos a cada mordida.', 15.90, now());
INSERT INTO produtos (id_externo, categoria, nome, descricao, preco, data_criacao) VALUES (gen_random_uuid(), 'ACOMPANHAMENTO', 'Anéis de cebola (400g)', 'Anéis de cebola empanados e dourados, crocantes e saborosos a cada mordida.', 19.90, now());

INSERT INTO produtos (id_externo, categoria, nome, descricao, preco, data_criacao) VALUES (gen_random_uuid(), 'BEBIDA', 'Refrigerante Guaraná Antarctica Lata 350ml', 'Refrescante e gelado, ideal para acompanhar qualquer refeição. Escolha o seu sabor favorito e aproveite!', 5.99, now());
INSERT INTO produtos (id_externo, categoria, nome, descricao, preco, data_criacao) VALUES (gen_random_uuid(), 'BEBIDA', 'Refrigerante Coca Cola Lata 350ml', 'Refrescante e gelado, ideal para acompanhar qualquer refeição. Escolha o seu sabor favorito e aproveite!', 5.99, now());
INSERT INTO produtos (id_externo, categoria, nome, descricao, preco, data_criacao) VALUES (gen_random_uuid(), 'BEBIDA', 'Refrigerante Fanta Laranja Lata 350ml', 'Refrescante e gelado, ideal para acompanhar qualquer refeição. Escolha o seu sabor favorito e aproveite!', 5.99, now());
INSERT INTO produtos (id_externo, categoria, nome, descricao, preco, data_criacao) VALUES (gen_random_uuid(), 'BEBIDA', 'Refrigerante Guaraná Antarctica 1 Litro', 'Refrescância na medida certa para compartilhar e aproveitar. Ideal para acompanhar refeições e momentos com amigos ou família!', 10.99, now());
INSERT INTO produtos (id_externo, categoria, nome, descricao, preco, data_criacao) VALUES (gen_random_uuid(), 'BEBIDA', 'Refrigerante Coca Cola 1 Litro', 'Refrescância na medida certa para compartilhar e aproveitar. Ideal para acompanhar refeições e momentos com amigos ou família!', 10.99, now());
INSERT INTO produtos (id_externo, categoria, nome, descricao, preco, data_criacao) VALUES (gen_random_uuid(), 'BEBIDA', 'Refrigerante Fanta Laranja 1 Litro', 'Refrescância na medida certa para compartilhar e aproveitar. Ideal para acompanhar refeições e momentos com amigos ou família!', 10.99, now());
INSERT INTO produtos (id_externo, categoria, nome, descricao, preco, data_criacao) VALUES (gen_random_uuid(), 'BEBIDA', 'Suco de Laranja 300ml', 'Refrescantes e naturais, preparados com frutas selecionadas. A escolha perfeita para quem busca sabor e saúde em cada gole!', 7.99, now());
INSERT INTO produtos (id_externo, categoria, nome, descricao, preco, data_criacao) VALUES (gen_random_uuid(), 'BEBIDA', 'Suco de Laranja 500ml', 'Refrescantes e naturais, preparados com frutas selecionadas. A escolha perfeita para quem busca sabor e saúde em cada gole!', 12.99, now());
INSERT INTO produtos (id_externo, categoria, nome, descricao, preco, data_criacao) VALUES (gen_random_uuid(), 'BEBIDA', 'Suco de Laranja Jarra 1 Litro', 'Delicie-se com nossos sucos frescos e naturais, servidos em uma jarra generosa.', 20.99, now());

INSERT INTO produtos (id_externo, categoria, nome, descricao, preco, data_criacao) VALUES (gen_random_uuid(), 'SOBREMESA', 'Açaí Tradicional 350ml', 'Açaí Tradicional refrescante e energético, preparado com açaí puro e cremoso.', 14.90, now());
INSERT INTO produtos (id_externo, categoria, nome, descricao, preco, data_criacao) VALUES (gen_random_uuid(), 'SOBREMESA', 'Açaí Tradicional 500ml', 'Açaí Tradicional refrescante e energético, preparado com açaí puro e cremoso.', 22.90, now());
INSERT INTO produtos (id_externo, categoria, nome, descricao, preco, data_criacao) VALUES (gen_random_uuid(), 'SOBREMESA', 'Açaí Tradicional 1000ml', 'Açaí Tradicional refrescante e energético, preparado com açaí puro e cremoso.', 30.90, now());