server:
  port: 8082
spring:
  application:
    name: produto-ms
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/produto-ms
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  flyway:
    enabled: true
    locations: 'classpath:db/migration'
    validate-on-migrate: false