server:
  port: 8081
spring:
  application:
    name: clientes-ms
  mvc:
    servlet:
      path: /api/clientes
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/clientes-ms
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  flyway:
    enabled: true
    locations: 'classpath:db/migration'
    validate-on-migrate: false